#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir//bin/sh" ]; then
  "$basedir//bin/sh"  "$basedir/../Data/global/node_modules/.bin/create-vite" "$@"
  ret=$?
else 
  /bin/sh  "$basedir/../Data/global/node_modules/.bin/create-vite" "$@"
  ret=$?
fi
exit $ret
